### ISSUE TITLE
Cannot set fixed outlier coefficients

### ISSUE THREAD

**Issue by a-s-russo** [jdemetra/jdplus-main#398] opened 2024-08-23 02:01 UTC
Consider inserting an additive outlier (AO) in a series and setting the 'parameter value' as follows:

![image](https://github.com/user-attachments/assets/c39cd55e-39f2-4310-a502-e9528b20a97c)

After clicking on Ok and then applying the changes, the parameter value seems to have 'disappeared'. If I reopen the 'Pre-specified outliers' dialogue box, the parameter value is no longer visible:

![image](https://github.com/user-attachments/assets/03f51298-2225-44bc-95e7-88912b3a8669)

The AO is being applied to my series with a value of one in the Regressors matrix as expected (Pre-processing -> Regressors), but not with the parameter value I used:

![image](https://github.com/user-attachments/assets/ece74446-2ddf-488c-8b58-7bbf0d710d47)

Instead of 1.15 I input previously, the above suggests that -0.0043 is being used instead.

I use the term 'value' to refer to the regressor number (which is 1 in this case), and I use the term 'coefficient' for the factor that RegARIMA estimates for the size of the correction (which I want to set to 1.15 in this case).

- How do I insert a fixed factor?
- What does 'parameter value' in JD+ mean?
- Does it refer to 'value' or 'coefficient' as per my definitions?
- Why does the 'parameter value' seem to 'disappear' when I reopen the relevant dialogue box?
- And why does it not appear in the underlying XML file (see screen shot below)?

![image](https://github.com/user-attachments/assets/c25bbc7f-e240-4178-906e-4ce7a291a984)

Note that I have been able to successfully specify fixed coefficients via RJDemetra, as shown below with a separate example:

![image](https://github.com/user-attachments/assets/66e8d927-3e0a-4415-a258-ffcec989c6d7)

If the coefficient is fixed, and the value of the fixed coefficient is 0, will JD+ re-estimate it via RegARIMA, or will it use a coefficient of 0 (meaning that the outlier in effect is not applied to the series)?

The same issue above occurs for LSs as well. The above was done using a single document, not a multi-document, and used JD+ version 3.2.4.

**Comment by Immurb** [comment] 2024-08-27 06:56
It is only possible to fix any coefficients in the GUI if the transformation is defined (aka not Auto). **We should definitely make it clear for the user, by deactivating the option and explaining the cause in the description.**

So let me answer all the questions:

- How do I insert a fixed factor?
First set a transformation (Log or None), then set the factor.
- What does 'parameter value' in JD+ mean? / Does it refer to 'value' or 'coefficient' as per my definitions?
It is the coefficient and is named that way in TradingDays and User-defined variables. **I will change it to be more consistent and specific**.
- Why does the 'parameter value' seem to 'disappear' when I reopen the relevant dialogue box? / And why does it not appear in the underlying XML file (see screen shot below)?
If no transformation is defined JDemetra changes the 'parameter value' to 0 Undefined when closing the box, so, it really disappears.
- If the coefficient is fixed, and the value of the fixed coefficient is 0, will JD+ re-estimate it via RegARIMA, or will it use a coefficient of 0 (meaning that the outlier in effect is not applied to the series)?
It will use and show it as a fixed outlier with coefficient of 0.

**Comment by a-s-russo** [comment] 2024-08-27 22:37
Thanks so much for the helpful answers @Immurb. I appreciate you answering each of my questions carefully. That all makes sense. I look forward to having your suggestion of making things clearer for the user implemented.

**Comment by a-s-russo** [comment] 2024-08-28 02:50
One further thing to add @Immurb: there was a reason for my question regarding the meaning of 0 for fixed coefficients:

In R, when we look up the documentation for the `add_outlier()` function, under `Arguments` it says "coef: the coefficient if needs to be fixed. **If equal to 0 the outliers/ramps coefficients are estimated.**

Why does the R interface differ to the GUI? It seems that in RJDemetra, a 0 tells JD+ to re-estimate, but in the GUI, it doesn't mean that.

We're not sure why in R the default value of `coef` isn't NULL or NA so that any value given to it would indicate a fixed value but if it's NULL/NA then RegARIMA would re-estimate.

**Comment by Immurb** [comment] 2024-09-03 10:26
I'm not sure why it is implemented that way in R, maybe @TanguyBarthelemy or @charphi know.
Internally each Parameter/Coefficient has a value and a type (Undefined, Initial, Fixed, Estimated). In the GUI I think you can only choose the type for ARIMA parameters, everything else fixes the value.

**Comment by palatej** [comment] 2024-09-03 14:08
A few clarifications:

We use the same structure for parameters (in ARIMA or other models) and for regression coefficients. Not the best choice, but changing it would be expensive and error prone. 
At least, we should indeed adapt the spec boxes to use the correct names and to hide the coefficients when they can't be fixed. The documentation should explain why. I will add it in the issues.

In the ARIMA model, the different types make sense: you can of course estimate the value or fix it, but you can also give an initial value; that is useful when there are different local maximum likelihood solutions (different initial values could give different final estimates).

Considering the coefficients of the regression, you just can fix them or estimate them: there is an analytic solution and initial values would never be used. That's why given coefficients are always considered as fixed. Using 0 doesn't make sense in most cases. The only exception is trading days, when you want to exclude the effects of some day(s).

The choice of the default value in R is indeed misleading. NULL or NA would be better. To be noted that 0 is automatically changed in the R code to NULL. -> small improvement for the next release (-> issue in rjd3toolkit)

**Comment by a-s-russo** [comment] 2024-09-04 01:14
Thanks for the clarifications @Immurb and @palatej. Incorporating the suggested changes in a future release would be great.

I agree that a coefficient of 0 is pointless in all cases except for the one @palatej has identified. However, the GUI treatment is better in my view than the R treatment: the former is helpfully consistent regardless of value if type is 'fixed', even if the value is 0. That is easier to understand than having 0 mean 're-estimate' as per the R implementation.

**Comment by a-s-russo** [comment] 2024-09-04 04:52
I have one more question given the replies above. @Immurb stated that in the GUI, the 'type can only be set for ARIMA parameters'. However, @palatej then said that for the regression coefficients, 'you just can fix them or estimate them', but then goes on to say that they 'are always considered as fixed'.

I'm confused now: are the coefficients for user-defined variables (regressors) always fixed, always re-estimated, or can the user choose the type ('fixed', or 're-estimate'). If so, how (in the GUI)?

Similar to LSs and AOs, I can't make sense of the corresponding user-defined variable window (even if I choose a non-auto transformation as @Immurb advised):

![image](https://github.com/user-attachments/assets/a273bb7f-78d8-402d-b624-dd064fa44870)

**Comment by palatej** [comment] 2024-09-06 07:30
If you give a value, the coefficient is considered as fixed. Otherwise, it is (of course) estimated. 

To be noted that the treatment of fixed coefficients is completely different from usual REGARIMA estimation: fixed regression effects are first removed from the series; that's why we must now the transformation of the series to interpret it correctly (should they be applied on the series in levels or in logs?) . The modified series is then processed and the fixed regression effects are finally reintroduced in the results. 

More details can be retrieve in the [documentation ](https://jdemetra-new-documentation.netlify.app/a-sa-pre-treatment)

**Closed by palatej** 2024-09-06 07:30 UTC
Labels: enhancement

**Comment by a-s-russo** [comment] 2024-11-13 04:39
Hi again @palatej. I have a further question regarding your comment above: _"If you give a value, the coefficient is considered as fixed. Otherwise, it is (of course) estimated."_

In the underlying XML workspace file, what is the data item name for coefficients that are estimated rather than fixed?

When the coefficients are fixed, the tag label is clearly displayed:

![image](https://github.com/user-attachments/assets/b491134a-8955-4bd0-ac1b-e519db4bfc87)

However, what is the tag name for when the coefficient is not fixed? Is it 'Estimated', or 'Undefined', or 'Initial', or something else, or does it simply not appear in the XML file? **Also**, does the answer depend on whether the workspace file is a single document or a multi-document?

**Comment by palatej** [comment] 2024-11-13 17:24
The xml is the same for single or multi-document (more exactly, the xml in a single document is an extract of the xml in a multi-document)

Some general rules for the parameters (regression or arima)
- Input parameters (given by the user)
   -   "Fixed", "Undefined", "Initial" are reserved to input parameters.
   -   "Estimated" is considered as "Undefined" in inputs (but such parameters can be changed in "Fixed" parameters if you use suitable refreshing policies) 
   -   "Initial" is only meaningful for arima parameters.
   -   "Initial" in regression is considered as "Undefined 

- Output parameters (generated by the processing)
   -  "Fixed", "Estimated" are reserved to output parameters (results of the processing)
   -  "Fixed" inputs give "Fixed" outputs
   -  Other inputs give "Estimated" outputs

**Comment by a-s-russo** [comment] 2024-11-14 01:18
Thanks @palatej for your prompt reply. That information has helped to clarify the situation for us.
