### ISSUE TITLE
names lost when importing data to utilities 

### ISSUE THREAD

**Issue by annasmyk** [jdemetra/jdplus-main#273] opened 2024-04-22 15:50 UTC
names lost when importing data to utilities : in v2 at least names in labels, in v 3.2.2, no names at all, the user has to rename carefully according to order of dragging from provider

**Comment by charphi** [comment] 2024-06-07 14:15
Duplicate of https://github.com/jdemetra/jdplus-main/issues/291

**Closed by charphi** 2024-06-07 14:15 UTC
Labels: bug
